### ISSUE TITLE
Unhandled rejection when connection to proxy fails

### ISSUE THREAD

**Issue by petrpatek** [apify/got-scraping#14] opened 2021-04-13 07:26 UTC
Connected to https://github.com/szmarczak/http2-wrapper/issues/66.
```
(node:12200) UnhandledPromiseRejectionWarning: Error: The proxy server rejected the request with status code 502
    at Http2OverHttp.createConnection (G:\www\amazon\node_modules\got-scraping\node_modules\http2-wrapper\source\proxies\h2-over-hx.js:19:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async entry (G:\www\amazon\node_modules\got-scraping\node_modules\http2-wrapper\source\agent.js:395:15)
(node:12200) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7) 
```

**Comment by mnmkng** [comment] 2021-04-13 09:43
I wonder whether we're not getting the rejections because we're using the proxy classes directly and we need to wrap them in some handlers ourselves https://github.com/apify/got-scraping/blob/fb4b9f460fa9474062310ace1d2851af3bf12029/src/handlers/proxy.js#L12

**Comment by szmarczak** [comment] 2021-04-13 14:47
Are you able to reproduce the issue?

**Comment by mnmkng** [comment] 2021-04-13 16:45
@szmarczak We tried to create a minimal repro, but without success so far. The error happened in a production run that's making millions of requests. We'll keep trying to reproduce it though.

**Comment by szmarczak** [comment] 2021-07-20 17:10
Hmmm... With https://github.com/apify/got-scraping/blob/fa12f72ea1b7da76bb3121c59c2175cf09710a12/src/hooks/alpn.js#L30 this shouldn't happen at all...

**Comment by mnmkng** [comment] 2021-07-20 17:45
@szmarczak it's hopefully fixed now in master. At least it seems so from our testing. I wanted to close this only when we fully release the changes. The version in master needs Node 15+ so it's a breaking change and we need to update our SDK to node 15+ as well. Sorry for the confusion.

**Comment by mnmkng** [comment] 2021-07-20 17:45
Fixed in master.

**Closed by mnmkng** 2021-07-20 17:45 UTC
Labels: bug
